# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [8]:
np.version.version

'1.19.5'

#### Q3 : Créer un vecteur nul de taille 10

In [20]:
np.zeros(10, dtype = np.int) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [30]:
np.zeros(10, dtype = np.int)[3] = 4
toto[3] = 4
toto

array([0, 0, 0, 4, 0, 0, 0, 0, 0, 0])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [31]:
z = np.arange(10, 51, 1)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [56]:
z = np.arange(50, 9, -1)
z

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [57]:
np.arange(0, 9, 1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [70]:
np.random.random((3, 3, 3))

array([[[0.24812513, 0.78294402, 0.10868973],
        [0.23423667, 0.97209072, 0.71120449],
        [0.96893562, 0.77625669, 0.4038834 ]],

       [[0.85422884, 0.32863174, 0.193039  ],
        [0.19186895, 0.9312254 , 0.93889833],
        [0.58568468, 0.33059954, 0.32669873]],

       [[0.29694969, 0.83895785, 0.13315573],
        [0.88682753, 0.99939867, 0.04128661],
        [0.80987201, 0.09232806, 0.88546227]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [93]:
matrix = np.random.random((10, 10))

matrix.min(), matrix.max()

(0.009852917827615437, 0.996620692750088)

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [105]:

v = np.arange(1, 5, 1)
np.diag(v,-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [125]:
x = np.random.random(5)
print(x)
x.sum()

[0.580912   0.8621034  0.59486247 0.68408712 0.6939946 ]


3.41595958916229

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [126]:
print(x)
x.mean()

[0.580912   0.8621034  0.59486247 0.68408712 0.6939946 ]


0.683191917832458

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [134]:
np.size(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [3]:
x = np.random
x.rand(10)

array([0.75924526, 0.61022531, 0.07897675, 0.950485  , 0.56110954,
       0.0199587 , 0.30328055, 0.28532149, 0.42816376, 0.09900595])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [15]:
a = np.random.random(5)
b = np.random.random(5)

(a == b).all()

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [32]:
array = np.array((np.random.random(10)*10), dtype='float32')
print(array)
array2 = array.astype(np.int32)
print(array2)

[9.751692   2.7336104  5.9616833  4.1919246  0.54900336 6.895359
 5.1847873  6.2264924  7.140415   5.681433  ]
[9 2 5 4 0 6 5 6 7 5]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [40]:
x = np.random.random((5,5))
print(x)
x = x*10
print(x)
moyenne = x.mean()
print(moyenne)
ecart = np.std(x)
print(ecart)
normalize = (np.sum(x) - moyenne) / ecart
print(normalize)

[[0.30462152 0.04056454 0.94855646 0.30941897 0.63129654]
 [0.7800161  0.68437333 0.42172732 0.54263359 0.03297094]
 [0.83854511 0.10742934 0.51455866 0.28055109 0.58697102]
 [0.20542934 0.13709692 0.74771815 0.41995526 0.53352914]
 [0.27942467 0.16619886 0.8530269  0.39611791 0.40747843]]
[[3.04621518 0.40564545 9.48556461 3.09418975 6.31296543]
 [7.80016098 6.84373327 4.21727321 5.42633587 0.32970942]
 [8.38545113 1.07429341 5.14558661 2.80551092 5.86971023]
 [2.05429335 1.37096921 7.47718154 4.19955261 5.33529138]
 [2.79424669 1.66198859 8.530269   3.96117914 4.07478427]]
4.468084049563198
2.598327606605502
41.27039905087605


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [51]:
m = np.random.random((2, 2))
print(m)
m2 = np.transpose(m)
print(m2)

[[0.25849087 0.96946399]
 [0.32708824 0.36923707]]
[[0.25849087 0.32708824]
 [0.96946399 0.36923707]]


#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [84]:
z = np.zeros((10,10))
print(z)
v = int(np.random.random()*10)
t = int(np.random.random()*10)
np.put(z, v, t)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)