In [2]:
import numpy as np

# Quelques fonctions utiles

On a créé un tableau 2D `rdm_mat` contenant des valeurs aléatoires. 

In [7]:
rdm_mat = np.random.random((2,2)) * 10
rdm_mat = np.array(rdm_mat, dtype='int')
print(rdm_mat)

[[8 5]
 [6 8]]


Donner le type de la variable rdm_mat

In [9]:
rdm_mat.dtype

dtype('int32')

Donner la somme des éléments de ce tableau 2D

In [12]:
print(rdm_mat)
np.sum(rdm_mat)

[[8 5]
 [6 8]]


27

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [20]:
np.max(rdm_mat, axis=1).max()

8

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [21]:
np.max(rdm_mat, axis=0).max()

8

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

On crée un vecteur aléatoire de taille 100 `rdm_vect`

In [29]:
rdm_vect = np.random.randn(100)
rdm_vect

array([ 2.06792859,  0.05573472,  1.01580377, -0.79669878,  1.03632782,
        0.68767296,  1.03957473, -0.60716086, -1.31439155,  0.58597258,
       -1.73736768, -0.01561867,  0.5142159 , -0.48124219, -0.47428177,
        1.02606369, -1.51246073, -2.09466824,  0.31849174, -1.14813898,
        0.8206278 , -2.32198054, -0.8952578 , -0.22764561, -0.57595704,
        2.36978174,  0.86792944,  2.39059233,  1.24168127, -0.42082041,
       -1.22437246,  0.22880579, -0.46289892,  1.00469151, -1.31707612,
        0.85385291,  0.81136262,  0.57038823,  0.48197592,  0.79187445,
       -0.64919764,  0.62394005, -0.50587392, -2.07273063,  1.73780237,
       -0.61246727, -0.58862775, -0.00522313,  0.87944385, -0.41922789,
       -0.52926441, -1.55975971, -0.69924626,  1.50521056,  1.1802226 ,
       -0.12801658,  1.56286914,  0.40797641,  0.77210832,  1.62605591,
        0.08317317, -0.34161019, -1.0378878 ,  0.05570816, -0.54463744,
       -0.96285567, -0.50787903,  0.76975482,  1.35051586,  0.50

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [30]:
np.argmax(rdm_vect)

27

Afficher cette valeur 

In [31]:
rdm_vect.max()

2.3905923337170307

Convertir le vecteur en un tableau 10, 10

In [32]:
rdm_vect.reshape(10, 10)

array([[ 2.06792859,  0.05573472,  1.01580377, -0.79669878,  1.03632782,
         0.68767296,  1.03957473, -0.60716086, -1.31439155,  0.58597258],
       [-1.73736768, -0.01561867,  0.5142159 , -0.48124219, -0.47428177,
         1.02606369, -1.51246073, -2.09466824,  0.31849174, -1.14813898],
       [ 0.8206278 , -2.32198054, -0.8952578 , -0.22764561, -0.57595704,
         2.36978174,  0.86792944,  2.39059233,  1.24168127, -0.42082041],
       [-1.22437246,  0.22880579, -0.46289892,  1.00469151, -1.31707612,
         0.85385291,  0.81136262,  0.57038823,  0.48197592,  0.79187445],
       [-0.64919764,  0.62394005, -0.50587392, -2.07273063,  1.73780237,
        -0.61246727, -0.58862775, -0.00522313,  0.87944385, -0.41922789],
       [-0.52926441, -1.55975971, -0.69924626,  1.50521056,  1.1802226 ,
        -0.12801658,  1.56286914,  0.40797641,  0.77210832,  1.62605591],
       [ 0.08317317, -0.34161019, -1.0378878 ,  0.05570816, -0.54463744,
        -0.96285567, -0.50787903,  0.76975482

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [40]:
np.mean(rdm_vect, axis=0)

0.08947470100378804

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

In [42]:
np.sum()

print(np.cumsum(rdm_vect, axis=0))
print(len(rdm_vect))

[ 2.06792859  2.12366331  3.13946708  2.3427683   3.37909611  4.06676908
  5.10634381  4.49918295  3.1847914   3.77076398  2.0333963   2.01777763
  2.53199353  2.05075134  1.57646956  2.60253325  1.09007253 -1.00459572
 -0.68610398 -1.83424296 -1.01361516 -3.33559569 -4.2308535  -4.4584991
 -5.03445615 -2.66467441 -1.79674496  0.59384737  1.83552864  1.41470823
  0.19033577  0.41914156 -0.04375736  0.96093415 -0.35614197  0.49771094
  1.30907356  1.87946179  2.3614377   3.15331216  2.50411451  3.12805456
  2.62218064  0.54945002  2.28725239  1.67478512  1.08615737  1.08093424
  1.96037809  1.5411502   1.0118858  -0.54787392 -1.24712018  0.25809038
  1.43831298  1.3102964   2.87316554  3.28114195  4.05325026  5.67930617
  5.76247934  5.42086915  4.38298135  4.4386895   3.89405206  2.9311964
  2.42331737  3.19307218  4.54358804  5.0483782   6.03621755  4.68179534
  3.03978742  4.63771045  6.4767246   6.64929488  6.31195613  6.89469427
  7.54939459  7.2921238   7.47095948  8.12338072  8.6

Calculer la somme pour chaque ligne (sans boucles)

array([-2.45928276e+00,  3.30057119e+00, -6.94069374e-01,  1.16367130e-01,
       -7.35080583e-01,  1.78359994e-03, -1.12472416e+00,  9.99337195e+00,
       -1.69671892e+00,  1.56672647e+00])